### ISSUE TITLE
error importing `rotini` with typescript@4.9.5

### ISSUE THREAD

**Issue by KingOfTac** [matthewgetz/rotini#2]
Typescript seems to not like the default export from the package.

## Console output:
```shell
error TS2349: This expression is not callable.
  Type 'typeof import("/node_modules/rotini/build/index")' has no call signatures.

9  const program = rotini({
```

## Environment
* Node 19.3.0
* npm 9.2.0
* typescript 4.9.5

using `type: module` in package.json and `ESNext` module option in `tsconfig.json`

**Comment by matthewgetz** [comment]
@KingOfTac rotini does not currently support esm. If you switch to "type": "commonjs" in your package.json the import should work as intended.

**Comment by KingOfTac** [comment]
> @KingOfTac rotini does not currently support esm. If you switch to "type": "commonjs" in your package.json the import should work as intended.

Any plans to support it? I'd love to use this package, however esm is a hard requirement for my use case.

**Comment by matthewgetz** [comment]
@KingOfTac yep! looking to get esm support in the next release. if you can develop against cjs for now, you should be able to switch over to esm once the next version is released.

**Comment by KingOfTac** [comment]
Awesome, will do.
